INSERT INTO USER(USERNAME, PASSWORD) VALUES('alberto','12345');
INSERT INTO USER(USERNAME, PASSWORD) VALUES('paco','23456');
INSERT INTO USER(USERNAME, PASSWORD) VALUES('manolo','74E89ER');

INSERT INTO RECETA(NOMBRE, DIFICULTAD, ELABORACION) VALUES('Canelones',4,'Cocer los canelones y echarles el relleno.');